export const FETCH_PRODUCTS = {
  FETCHING: 'FETCH_PRODUCTS_FETCHING',
  SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  ERROR: 'FETCH_PRODUCTS_ERROR',
}

export const FETCH_PRODUCT_VERSIONS = {
  FETCHING: 'FETCH_PRODUCT_VERSIONS_FETCHING',
  SUCCESS: 'FETCH_PRODUCT_VERSIONS_SUCCESS',
  ERROR: 'FETCH_PRODUCT_VERSIONS_ERROR',
}

export const FETCH_BUGS = {
  FETCHING: 'FETCH_BUGS_FETCHING',
  SUCCESS: 'FETCH_BUGS_SUCCESS',
  ERROR: 'FETCH_BUGS_ERROR',
}
