export const FETCH_PRODUCTS = {
  FETCHING: 'FETCHING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
}

export const FETCH_PRODUCT_VERSIONS = {
  FETCHING: 'FETCHING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
}

export const FETCH_BUGS = 'FETCH_BUGS'
