export const FETCH_PRODUCTS_FETCHING = 'FETCH_PRODUCTS_FETCHING'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const FETCH_PRODUCT_VERSIONS_FETCHING = 'FETCH_PRODUCT_VERSIONS_FETCHING'
export const FETCH_PRODUCT_VERSIONS_SUCCESS = 'FETCH_PRODUCT_VERSIONS_SUCCESS'
export const FETCH_PRODUCT_VERSIONS_ERROR = 'FETCH_PRODUCT_VERSIONS_ERROR'

export const FETCH_BUGS = 'FETCH_BUGS'
