export const CHANGE_APP_TITLE_TO = {
  PRODUCTS: 'CHANGE_APP_TITLE_TO_PRODUCTS',
  VERSIONS: 'CHANGE_APP_TITLE_TO_VERSIONS',
  BUGS: 'CHANGE_APP_TITLE_TO_BUGS',
}

export const FETCH_PRODUCTS = {
  FETCHING: 'FETCH_PRODUCTS_FETCHING',
  SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  ERROR: 'FETCH_PRODUCTS_ERROR',
}

export const FETCH_PRODUCT_VERSIONS = {
  FETCHING: 'FETCH_PRODUCT_VERSIONS_FETCHING',
  SUCCESS: 'FETCH_PRODUCT_VERSIONS_SUCCESS',
  ERROR: 'FETCH_PRODUCT_VERSIONS_ERROR',
}

export const FETCH_BUGS = {
  FETCHING: 'FETCH_BUGS_FETCHING',
  SUCCESS: 'FETCH_BUGS_SUCCESS',
  ERROR: 'FETCH_BUGS_ERROR',
}
